[project]
name = "sbtc-payment-gateway"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.sbtc-payment]
path = "contracts/sbtc-payment.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
